
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"img/")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


root = Tk()

root.geometry("725x522")
root.configure(bg = "#110D20")


canvas = Canvas(
    root,
    bg = "#110D20",
    height = 522,
    width = 725,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_bg.png"))
image_1 = canvas.create_image(
    304.0,
    431.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_title.png"))
image_2 = canvas.create_image(
    362.0,
    133.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_send0.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_send clicked"),
    relief="flat"
)
button_1.place(
    x=44.0,
    y=241.0,
    width=297.0,
    height=65.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_receive0.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_receive clicked"),
    relief="flat"
)
button_2.place(
    x=384.0,
    y=241.0,
    width=297.0,
    height=65.0
)
root.resizable(False, False)
root.mainloop()
