
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"img/")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("725x522")
window.configure(bg = "#120E20")


canvas = Canvas(
    window,
    bg = "#120E20",
    height = 522,
    width = 725,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    362.0,
    117.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    131.0,
    91.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_send.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_send clicked"),
    relief="flat"
)
button_1.place(
    x=495.0,
    y=160.0,
    width=192.0,
    height=202.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_upload.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=47.0,
    y=161.0,
    width=413.0,
    height=201.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    367.0,
    442.0,
    image=image_image_3
)

canvas.create_text(
    57.0,
    424.0,
    anchor="nw",
    text="id: 123456789",
    fill="#120E20",
    font=("ArialRoundedMTBold", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
